name: aphinity

services:
  app:
    build:
      context: .
    # NGINX is bound to this loopback interface as well
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - aim-network
    extra_hosts:
      - "host.docker.internal:172.18.0.1"
    env_file:
      - .env.runtime
    volumes:
      - ${LOG_HOST_DIR:-./logs}:/logs
    environment:
      - LOG_DIR=/logs

networks:
  aim-network:
    external: true
    name: aim-network
    driver: bridge