create table if not exists service_event_audit_log (
    id bigint generated by default as identity primary key,
    service_event_id bigint not null,
    location_id bigint not null,
    actor_user_id bigint not null,
    action varchar(16) not null,
    title varchar(42) not null,
    responsibility varchar(16) not null,
    event_date date not null,
    event_time time not null,
    end_event_date date not null,
    end_event_time time not null,
    description text,
    status varchar(16) not null,
    service_event_created_at timestamp with time zone not null,
    service_event_updated_at timestamp with time zone not null,
    recorded_at timestamp with time zone not null default current_timestamp
);

create index if not exists service_event_audit_log_service_event_idx
    on service_event_audit_log (service_event_id, recorded_at);

create index if not exists service_event_audit_log_location_idx
    on service_event_audit_log (location_id, recorded_at);
