create table if not exists email_verification_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone default current_timestamp not null,
    constraint fk_email_verification_token_user
        foreign key (user_id) references app_user (id) on delete cascade
);

create index if not exists email_verification_token_user_id_idx
    on email_verification_token (user_id);

create unique index if not exists email_verification_token_token_hash_uq
    on email_verification_token (token_hash);

create table if not exists password_reset_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone default current_timestamp not null,
    constraint fk_password_reset_token_user
        foreign key (user_id) references app_user (id) on delete cascade
);

create index if not exists password_reset_token_user_id_idx
    on password_reset_token (user_id);

create unique index if not exists password_reset_token_token_hash_uq
    on password_reset_token (token_hash);
